language: php

dist: jammy
addons:
    apt:
        packages:
        - "libonig5"

php:
  - '8.2'

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs src --standard=psr2
